source "https://rubygems.org"

gem 'cucumber'
gem 'capybara'
gem 'poltergeist'
gem 'rspec'
gem 'phantomjs'
gem 'phantomjs-binaries'
gem 'show_me_the_cookies'
gem 'yard-cucumber', '>= 2.2.3'
gem 'selenium-webdriver', '2.45.0'
