source "https://rubygems.org"

gem 'cucumber'
gem 'capybara', '>= 2.8.1'
gem 'poltergeist', '>= 1.10.0'
gem 'rspec'
gem 'phantomjs'
gem 'phantomjs-binaries'
gem 'show_me_the_cookies', '>= 3.1.0'
gem 'yard-cucumber'
gem 'selenium-webdriver', '2.45.0'
