pipeline:
  build_6:
    image: node:6
    commands:
      - npm --loglevel warn install
      - npm test
    when:
      event: [push, pull_request]

  build_7:
    image: node:7
    commands:
      - npm --loglevel warn install
      - npm test
    when:
      event: [push, pull_request]

  build_app:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t gro .
    when:
      event: pull_request

  build_app:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t gro .
    when:
      branch: master

  build_acceptance:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -f Dockerfile-acceptance -t acceptance .
    when:
      event: pull_request

  build_acceptance:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -f Dockerfile-acceptance -t acceptance .
    when:
      branch: master

  test_acceptance:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker run -d --userns host --net host redis
      - docker run -d -e NODE_ENV=ci --net host --userns host gro
      - docker run --rm --net host --userns host acceptance
      - docker rm -vf "gro" "redis"
    when:
      event: pull_request

  test_acceptance:
    image: docker:17.09.1
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker run -d --userns host --net host redis
      - docker run -d -e NODE_ENV=ci --net host --userns host gro
      - docker run --rm --net host --userns host acceptance
      - docker rm -vf "gro" "redis"
    when:
      branch: master

  image_to_quay:
    image: docker:17.09.1
    secrets:
      - DOCKER_PASSWORD
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker login -u="ukhomeofficedigital+gro_form" -p=$${DOCKER_PASSWORD} quay.io
      - docker tag gro quay.io/ukhomeofficedigital/gro-form:$${DRONE_COMMIT_SHA}
      - docker push quay.io/ukhomeofficedigital/gro-form:$${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: push

  trigger_deploy_to_gro_form_dev:
    image: quay.io/ukhomeofficedigital/drone-trigger:v0.3.0
    secrets:
      - DRONE_TOKEN
    drone_server: https://drone.acp.homeoffice.gov.uk
    repo: UKHomeOffice/kube-gro
    branch: master
    deploy_to: dev
    params: APP_IMAGE_TAG=${DRONE_COMMIT_SHA},KUBE_NAMESPACE=gro-form-dev
    when:
      branch: master
      event: push

  trigger_deploy_to_gro_form_preprod:
    image: quay.io/ukhomeofficedigital/drone-trigger:v0.3.0
    secrets:
      - DRONE_TOKEN
    drone_server: https://drone.acp.homeoffice.gov.uk
    repo: UKHomeOffice/kube-gro
    branch: master
    deploy_to: preprod
    params: APP_IMAGE_TAG=${DRONE_COMMIT_SHA},KUBE_NAMESPACE=gro-form-preprod
    when:
      event: deployment
      environment: preprod
