app:
  build: .
  env_file: secrets.env
  environment:
    - NODE_ENV=docker-compose
    - EMAIL_IGNORE_TLS=true
    - CASEWORKER_EMAIL=a@user.com
  net: "host"
  ports:
    - "8080:8080"
  volumes:
    - "/public"
redis:
  image: redis
  net: "host"

nginx-proxy:
  image: quay.io/ukhomeofficedigital/nginx-proxy:v1.2.3
  net: "host"
  environment:
    - PROXY_SERVICE_HOST=127.0.0.1
    - PROXY_SERVICE_PORT=8080
    - NAXSI_USE_DEFAULT_RULES=FALSE
    - ADD_NGINX_SERVER_CFG=add_header Cache-Control private;add_header X-Frame-Options "SAMEORIGIN" always;add_header X-Content-Type-Options "nosniff" always;add_header X-XSS-Protection "1; mode=block" always;location /public {add_header Cache-Control max-age=86400;add_header X-Frame-Options "SAMEORIGIN" always;add_header X-Content-Type-Options "nosniff" always;add_header X-XSS-Protection "1; mode=block" always;alias /public;}
  volumes:
    - ./public:/public
  ports:
    - "80"

maildev:
  image: djfarrelly/maildev
  net: "host"
  ports:
    - "8000"
    - "25"
