apiVersion: v1
kind: Service
metadata:
 labels:
   name: gro
 name: gro
spec:
 type: NodePort
 ports:
   - name: http
     port: 8080
     targetPort: 8080
     nodePort: 30241 
   - name: https
     port: 8080
     targetPort: 8080
     nodePort: 30242
 selector:
   name: gro
