apiVersion: v1
kind: ReplicationController
metadata:
  name: gro
spec:
  replicas: 3
  selector:
    name: gro
  template:
    metadata:
      labels:
        name: gro
    spec:
      containers:
      - name: app
        image: quay.io/ukhomeofficedigital/gro-form:v0.0.1
        imagePullPolicy: Always
        env:
        - name: NODE_ENV
          value: docker
        - name: REDIS_HOST
          value: redis.gro-form-dev.svc.cluster.local
        - name: REDIS_PORT
          value: "6379"
        ports:
        - containerPort: 8080
