apiVersion: v1
kind: ReplicationController
metadata:
  name: gro
spec:
  replicas: 3
  selector:
    name: gro
  template:
    metadata:
      labels:
        name: gro
    spec:
      containers:
      - name: tls
        image: ${tls_tag}
        imagePullPolicy: Always
        ports:
        - containerPort: 443
        - containerPort: 80
        env:
        - name: LOAD_BALANCER_CIDR
          value: '10.50.0.0/22'
        - name: PROXY_SERVICE_HOST
          value: 127.0.0.1
        - name: PROXY_SERVICE_PORT
          value: "8080"
        - name: ENABLE_UUID_PARAM
          value: "FALSE"
        - name: NAXSI_USE_DEFAULT_RULES
          value: "FALSE"
        volumeMounts:
          - name: external-tls
            mountPath: /etc/keys
            readOnly: true
      - name: app
        image: ${app_tag}
        imagePullPolicy: Always
        env:
        - name: NODE_ENV
          value: docker
        - name: POSTCODE_AUTH
          valueFrom:
            secretKeyRef:
              name: postcode-auth
              key: token
        - name: LISTEN_HOST
          value: "127.0.0.1"
        - name: PORT
          value: "8080"
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        ports:
        - containerPort: 8080
      volumes:
        - name: external-tls
          secret:
            secretName: external-tls
