apiVersion: v1
kind: Service
metadata:
 labels:
   name: gro
 name: gro
spec:
 type: NodePort
 ports:
   - name: http
     port: 80
     targetPort: 80
     nodePort: ${GRO_HTTP_PORT}
   - name: https
     port: 443
     targetPort: 443
     nodePort: ${GRO_HTTPS_PORT}
 selector:
   name: gro
