apiVersion: v1
kind: ReplicationController
metadata:
  name: gro
spec:
  replicas: 3
  selector:
    name: gro
  template:
    metadata:
      labels:
        name: gro
    spec:
      containers:
      - name: tls
        image: quay.io/ukhomeofficedigital/nginx-proxy:${tls_tag}
        imagePullPolicy: Always
        ports:
        - containerPort: 443
        - containerPort: 80
        env:
        - name: LOAD_BALANCER_CIDR
          value: '10.50.0.0/22'
        - name: PROXY_SERVICE_HOST
          value: 127.0.0.1
        - name: PROXY_SERVICE_PORT
          value: "8080"
        - name: ENABLE_UUID_PARAM
          value: "FALSE"
        - name: NAXSI_USE_DEFAULT_RULES
          value: "FALSE"
        - name: ERROR_REDIRECT_CODES
          value: "599"
        - name: ADD_NGINX_SERVER_CFG
          value: |
            add_header Cache-Control private;
            add_header X-Frame-Options "SAMEORIGIN" always;
            add_header X-Content-Type-Options "nosniff" always;
            add_header X-XSS-Protection "1; mode=block" always;
            location /public {
              add_header Cache-Control max-age=86400;
              add_header X-Frame-Options "SAMEORIGIN" always;
              add_header X-Content-Type-Options "nosniff" always;
              add_header X-XSS-Protection "1; mode=block" always;
              alias /public;
            }
        volumeMounts:
          - name: external-tls
            mountPath: /etc/keys
            readOnly: true
      - name: app
        image: quay.io/ukhomeofficedigital/gro-form:${app_tag}
        imagePullPolicy: Always
        env:
        - name: POSTCODE_AUTH
          valueFrom:
            secretKeyRef:
              name: postcode-auth
              key: token
        - name: NODE_ENV
          value: docker
        - name: LISTEN_HOST
          value: "127.0.0.1"
        - name: PORT
          value: "8080"
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        ports:
        - containerPort: 8080
        command:
          - "/app/run.sh"
      volumes:
        - name: external-tls
          secret:
            secretName: external-tls
