apiVersion: v1
kind: ReplicationController
metadata:
  name: redis
spec:
  replicas: 1
  selector:
    name: redis
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
      - name: redis
        image: quay.io/ukhomeofficedigital/redis:${ redis_tag }
        ports:
        - containerPort: 6379
        command:
        - "/run.sh"
        resources:
          limits:
            cpu: "0.2"
        volumeMounts:
        - mountPath: /var/lib/redis
          name: data
      volumes:
        - name: data
          emptyDir: {}
